version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - '.:/code'
  db:
    image: postgres:13
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=yatin
      - POSTGRES_PASSWORD=yatin
      - POSTGRES_DB=sportsbook